### ISSUE TITLE
[BUG]        Will not load with patch 2/0/5

### ISSUE THREAD

**Issue by Reguoc** [WittleWolfie/CharacterOptionsPlus#71] opened 2022-12-06 06:02 UTC
**Attach a Bug Report**
https://github.com/WittleWolfie/CharacterOptionsPlus#reporting-problems

**Describe the bug**

**To Reproduce**
2. Use '....'
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WittleWolfie** [comment] 2022-12-06 17:02
I cannot reproduce this and have no other reports. Please attach a bug report.

**Comment by WittleWolfie** [comment] 2022-12-13 02:41
Without a repro or bug report I can't do anything, closing out. Please re-open if you still have problems and attach logs.

**Closed by WittleWolfie** 2022-12-13 02:41 UTC
